### ISSUE TITLE
fix: banner not centred in preview layout

### ISSUE THREAD

**Issue by joemidi** [pyramidium/generator-bannertime#101]
I don't think we need the following position in the `base/main.js`

```js
TweenLite.set(banner, {top: 0, right: 0, bottom: 0, left: 0, position: 'absolute', margin: 'auto'});
```

as it shifts the banner to the wrong centre from the new `.banner` positioning below:

```scss
.banner {
  transform: translate(-50%, -50%);
  left: 50%;
  top: 50%;
}
```
