### ISSUE TITLE
fix: preloader does not fade out as intended

### ISSUE THREAD

**Issue by joemidi** [pyramidium/generator-bannertime#95]
Noticed in the most recent version of Chrome at least that the preloader no longer fades out on top of the creative.

Instead items instantly appear on the screen in place.

**Comment by joemidi** [comment]
I feel like [preloader.scss](https://github.com/pyramidium/generator-bannertime/blob/master/generators/app/templates/src/300x250/styles/base/preloader.scss) should include:

```scss
.preloader {
  position: absolute;
  background: #fff;
  height: 100%;
  width: 100%;
  z-index: 999;
}
```
